### ISSUE TITLE
Mods won't load

### ISSUE THREAD

**Issue by cantkillprogress** [flegald/GZDeck#12]
For some odd reason mods refuse to load in the launcher.

I have all my mods located in the "mods" folder, but even after I activate them I only get the base I WAD after I launch the game.

https://streamable.com/4xtss8

Maybe it's just a simple error on my part.

**Comment by flegald** [comment]
That's interesting. I can not reproduce in my testing. It also seems the selected IWAD is not being picked up either.

Just for my sanity's sake, would you mind sending the full path of where your IWAD and mods folder are please?

Thank you for the video too. That's a big help

**Comment by cantkillprogress** [comment]
> That's interesting. I can not reproduce in my testing. It also seems the selected IWAD is not being picked up either.
> 
> Just for my sanity's sake, would you mind sending the full path of where your IWAD and mods folder are please?
> 
> Thank you for the video too. That's a big help

No problem.

This is my file path:

$HOME/.var/.app/org.zdoom.GZDoom/.config/gzdoom

Mods are located in a folder called mods.

I believe this is all the correct pathing but I'm not 100% sure.

**Comment by flegald** [comment]
Hm yeah that seems correct.
Oh; I wonder, I have recently discovered that files with a space in the name are having trouble. Do any of the mods you are trying to load have spaces in the file names?

I am planning on getting that bug fix out soon

**Comment by flegald** [comment]
I have just pushed a release to fix spaces in folders/mods. Please let me know if it fixes it 🤞 
https://github.com/flegald/GZDeck/releases/tag/v1.5.0
